server:
  port: 8080
spring:
  database:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=GMT%2B8&useSSl=false
    username: root
    password: 123456a
    driver-class-name: com.mysql.cj.jdbc.Driver