server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=GMT%2B8&useSSl=false
    username: root
    password: 123456a
    driver-class-name: com.mysql.cj.jdbc.Driver
    server:
      tomcat:
        uri-encoding : UTF-8
    Debug: true